// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {
      name: 'Google',
      url: 'https://google.com',
      'x-twitter': 'youtube',
    },
    description:
      'The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.',
    license: {
      name: 'Creative Commons Attribution 3.0',
      url: 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService: 'https://developers.google.com/terms/',
    title: 'Gmail API',
    version: 'v1',
    'x-apiClientRegistration': {url: 'https://console.developers.google.com'},
    'x-apisguru-categories': ['analytics', 'media'],
    'x-logo': {
      url: 'https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png',
    },
    'x-origin': [
      {
        format: 'google',
        url: 'https://gmail.googleapis.com/$discovery/rest?version=v1',
        version: 'v1',
      },
    ],
    'x-providerName': 'googleapis.com',
    'x-serviceName': 'gmail',
  },
  servers: [{url: 'https://gmail.googleapis.com/'}],
} as const
export default oasMeta
