// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {
      name: 'Google',
      url: 'https://google.com',
      'x-twitter': 'youtube',
    },
    description: 'Reads and writes Google Sheets.',
    license: {
      name: 'Creative Commons Attribution 3.0',
      url: 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService: 'https://developers.google.com/terms/',
    title: 'Google Sheets API',
    version: 'v4',
    'x-apiClientRegistration': {url: 'https://console.developers.google.com'},
    'x-apisguru-categories': ['analytics', 'media'],
    'x-logo': {
      url: 'https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png',
    },
    'x-origin': [
      {
        converter: {
          url: 'https://github.com/mermade/oas-kit',
          version: '7.0.4',
        },
        format: 'google',
        url: 'https://sheets.googleapis.com/$discovery/rest?version=v4',
        version: 'v1',
      },
    ],
    'x-providerName': 'googleapis.com',
    'x-serviceName': 'sheets',
  },
  servers: [{url: 'https://sheets.googleapis.com/'}],
} as const
export default oasMeta
