// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {
      name: 'Google',
      url: 'https://google.com',
      'x-twitter': 'youtube',
    },
    description: 'Manipulates events and other calendar data.',
    license: {
      name: 'Creative Commons Attribution 3.0',
      url: 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService: 'https://developers.google.com/terms/',
    title: 'Calendar API',
    version: 'v3',
    'x-apiClientRegistration': {url: 'https://console.developers.google.com'},
    'x-apisguru-categories': ['analytics', 'media'],
    'x-logo': {
      url: 'https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png',
    },
    'x-origin': [
      {
        format: 'google',
        url: 'https://calendar-json.googleapis.com/$discovery/rest?version=v3',
        version: 'v1',
      },
    ],
    'x-providerName': 'googleapis.com',
    'x-serviceName': 'calendar',
  },
  servers: [{url: 'https://www.googleapis.com/calendar/v3'}],
} as const
export default oasMeta
