// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Files', version: 'v1.0'},
  servers: [{url: 'https://graph.microsoft.com/v1.0/', description: 'Core'}],
} as const
export default oasMeta
