// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Clerk Frontend API',
    version: 'v1',
    description:
      "The Clerk REST Frontend API, meant to be accessed from a browser or native environment.\n\nThis is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.\n\n### Versions\n\nWhen the API changes in a way that isn't compatible with older versions, a new version is released.\nEach version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).\n\n### Using the Try It Console\n\nThe `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme.\nTo use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.\n\nPlease see https://clerk.com/docs for more information.",
    'x-logo': {
      url: 'https://clerk.com/_next/image?url=%2Fimages%2Fclerk-logo.svg&w=96&q=75',
      altText: 'Clerk docs',
      href: 'https://clerk.com/docs',
    },
    contact: {
      email: 'support@clerk.com',
      name: 'Clerk Team',
      url: 'https://clerk.com/support',
    },
    termsOfService: 'https://clerk.com/terms',
    license: {
      name: 'MIT',
      url: 'https://github.com/clerk/javascript/blob/main/LICENSE',
    },
  },
  servers: [
    {
      url: 'https://{domain}.clerk.accounts.dev',
      variables: {
        domain: {
          default: 'example-destined-camel-13',
          description: 'Your Development Instance Frontend API Domain.',
        },
      },
    },
  ],
} as const
export default oasMeta
